name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Klon repozitorij
      - uses: actions/checkout@v4

      # 2) Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Instaliraj ovisnosti + ruff
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      # 4) Varijable okruženja za testove (DummyJSON bypass)
      - name: Export env
        run: |
          echo "BYPASS_DUMMY_AUTH=true" >> $GITHUB_ENV
          echo "JWT_SECRET=github-ci-secret" >> $GITHUB_ENV

      # 5) Pokreni testove
      - name: Run pytest
        run: pytest -q

      # 6) Lint s Ruff-om
      - name: Ruff check
        run: ruff check src tests
